### ISSUE TITLE
Get access to AWS with AWS educate pack

### ISSUE THREAD

**Issue by rafidalhaque** [livialima/linuxupskillchallenge#13]
Hi, 
How I can get access to AWS with AWS educate pack? Is it possible?

**Comment by livialima** [comment]
Signing up with AWS Educate pack:

1. Go to the AWS Educate website at https://aws.amazon.com/education/awseducate/
2. Click on the "Join AWS Educate" button located at the top right corner of the page.
3. Choose the option that best describes you, whether you are a student or an educator.
4. Create an AWS Educate account by filling out the required information, including your name, email address, and the name of your school or institution.
5. Once you have created your account, you can access the AWS Educate Starter Account, which includes $100 in AWS Promotional Credits, free access to over 25 AWS services, and self-paced labs and tutorials to help you get started with AWS.

Please note that the AWS Educate program is intended for students and educators who are interested in learning about cloud computing and AWS services. In order to be eligible for the program, you will need to provide proof of your status as a student or educator.
