### ISSUE TITLE
Day 10 - find a better use case of cron

### ISSUE THREAD

**Issue by livialima** [livialima/linuxupskillchallenge#54]
The original task of day 10 is to schedule system updates using cron.
Although this is a very easy task that beginners can jump right into, IRL is usually a bad idea.
Need to rewrite the lesson to a more realistic approach, using industry best practices. 

Suggestions are welcome and appreciated!

**Comment by kraker** [comment]
@livialima -- This is topical for me since I've been deeply immersed in cronjob stuff at work. Feel free to assign this issue to me if you like. A couple of use-cases I see on a regular basis are backups with `rsync` or cleaning up old files usually with some type of `find` command. I should be able to come up with a good example. 

Best practices probably should resemble Arabesque's I think: https://blog.sanctum.geek.nz/cron-best-practices/
